#!/usr/bin/env python3

# Using the ollama_web_app.py file as a starting point. I started by copying and pasting the python and html code, then modifying the html by hand to try to understand.
# Trying to learn basic html, so mostly searching up how to do things and using chatGPT to debug issues.
# Chat log: https://chatgpt.com/share/68df36ad-3204-800d-a3de-0f0b6b11b296

import eventlet
eventlet.monkey_patch()

from flask import Flask, Response, render_template, request, jsonify
from flask_socketio import SocketIO, send, emit
import requests
import json
import subprocess
import os
from bs4 import BeautifulSoup
import time
import base64
import wave
import io
from vosk import Model, KaldiRecognizer

app = Flask(__name__)
socketio = SocketIO(app, cors_allowed_origins="*")

# Ollama configuration
OLLAMA_URL = "http://localhost:11434"
DEFAULT_MODEL = "qwen2.5:0.5b-instruct-q4_0"

vosk_model = Model(lang="en-us")

def decode_audio(audio_bytes):
    # this function was generated by chatGPT
    """Convert webm/opus to PCM WAV using ffmpeg."""
    process = subprocess.Popen(
        ["ffmpeg", "-i", "pipe:0", "-ar", "16000", "-ac", "1", "-f", "s16le", "pipe:1"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )
    pcm_data, _ = process.communicate(audio_bytes)
    return pcm_data

def get_recipe_from_url(url):
    # this function was generated by chatGPT
    response = requests.get(url)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")

    # --- INGREDIENTS ---
    ingredients = []
    for li in soup.find_all("li", class_="wprm-recipe-ingredient"):
        amount = li.find("span", class_="wprm-recipe-ingredient-amount")
        unit = li.find("span", class_="wprm-recipe-ingredient-unit")
        name = li.find("span", class_="wprm-recipe-ingredient-name")

        ingredient_text = " ".join(
            filter(None, [
                amount.get_text(strip=True) if amount else None,
                unit.get_text(strip=True) if unit else None,
                name.get_text(strip=True) if name else None
            ])
        )
        if ingredient_text:
            ingredients.append(ingredient_text)

    # --- INSTRUCTIONS ---
    instructions = []
    for idx, li in enumerate(soup.find_all("li", class_="wprm-recipe-instruction"), start=1):
        step = li.find("div", class_="wprm-recipe-instruction-text")
        if step:
            step_text = step.get_text(" ", strip=True)  # preserve spaces in <span>/<div>
            instructions.append(f"Step {idx}: {step_text}")

    return {
        "ingredients": ingredients,
        "instructions": instructions
    }

conversation_context = None  # global or stored per-session

def query_ollama(prompt, model=DEFAULT_MODEL, system_text=None): # chatGPT generated
    """Query Ollama and return response with conversation memory support"""
    global conversation_context
    
    try:
        payload = {
            "model": model,
            "prompt": prompt,
            "stream": False
        }

        # Add system instruction if provided
        if system_text:
            payload["system"] = system_text

        # Add prior conversation context if it exists
        if conversation_context:
            payload["context"] = conversation_context

        response = requests.post(
            f"{OLLAMA_URL}/api/generate",
            json=payload,
            timeout=40
        )

        if response.status_code == 200:
            data = response.json()
            # Save context for future turns
            if "context" in data:
                conversation_context = data["context"]
            return data.get("response", "No response generated")
        else:
            return f"Error: Ollama returned status {response.status_code}"
    
    except requests.exceptions.Timeout:
        return "Sorry, the response took too long. Please try again."
    except Exception as e:
        return f"Error: {str(e)}"


def speak_text(text):
    """Simple text-to-speech using espeak"""
    # Clean text to avoid encoding issues
    clean_text = text.encode('ascii', 'ignore').decode('ascii')
    print(f"Assistant: {clean_text}")
    time.sleep(0.4)
    subprocess.run(['espeak', f'"{clean_text}"'], check=False)
    # this was debugged with chatGPT

@app.route('/')
def index():
    """Main web interface"""
    return render_template('baking_assistant.html')

@app.route('/api/chat', methods=['POST'])
def chat_api():
    """REST API endpoint for chat"""
    data = request.get_json()
    user_message = data.get('message', '')
    
    if not user_message:
        return jsonify({'error': 'No message provided'}), 400
    
    # Query Ollama
    response = query_ollama(user_message)
    
    return jsonify({
        'user_message': user_message,
        'ai_response': response
    })

@socketio.on('chat_message')
def handle_chat_message(data):
    """Handle chat message via WebSocket"""
    user_message = data.get('message', '')

    if user_message:
        # If it looks like a recipe link, scrape it
        if user_message.startswith("http://") or user_message.startswith("https://"):
            try:
                recipe = get_recipe_from_url(user_message)
                recipe_text = (
                    "📝 Ingredients:\n- " + "\n- ".join(recipe["ingredients"]) +
                    "\n\n👩‍🍳 Instructions:\n" + "\n".join(recipe["instructions"])
                )
                full_prompt = (
                    f"Here is the recipe that you're tasked with answering questions about:\n{recipe_text}\n\n"
                    "You are a helpful baking assistant offering to help with the recipe. Don't use emojis, only use plain text without astericks, and keep responses brief."
                )
                ai_response = query_ollama("Hi, who are you?", system_text=full_prompt) # manually edited
            except Exception as e:
                ai_response = f"⚠️ Sorry, I couldn’t parse that recipe link. Error: {str(e)}"
        else:
            # Otherwise, send message to Ollama
            ai_response = query_ollama(user_message)


        # Send response back to client
        emit('ai_response', {
            'user_message': user_message,
            'ai_response': ai_response
        })

# generated by chatGPT
@socketio.on('voice_recording')
def handle_voice_recording(data):
    """Handle raw audio recording, transcribe with Vosk, query Ollama, respond + speak"""
    try:
        audio_base64 = data.get("audio")
        #print(audio_base64)
        if not audio_base64:
            emit("ai_response", {"ai_response": "⚠️ No audio received."})
            return

        # Decode audio
        audio_bytes = base64.b64decode(audio_base64)

        # Convert to PCM with ffmpeg
        pcm_data = decode_audio(audio_bytes)

        rec = KaldiRecognizer(vosk_model, 16000)
        if rec.AcceptWaveform(pcm_data):
            result = json.loads(rec.Result())
        else:
            result = json.loads(rec.FinalResult())

        text_result = result.get("text", "")

        # while True:
        #     data = wf.readframes(4000)
        #     if len(data) == 0:
        #         break
        #     if rec.AcceptWaveform(data):
        #         result = json.loads(rec.Result())
        #         text_result += " " + result.get("text", "")
        # # Final result
        # final = json.loads(rec.FinalResult())
        # text_result += " " + final.get("text", "")
        print(text_result)

        user_message = text_result.strip()
        if not user_message:
            emit("ai_response", {"ai_response": "⚠️ Could not recognize speech."})
            return

        # Query Ollama
        ai_response = query_ollama(user_message)

        # Speak
        speak_text(ai_response)

        # Send back to client
        emit("ai_response", {
            "user_message": user_message,
            "ai_response": ai_response
        })

    except Exception as e:
        emit("ai_response", {"ai_response": f"⚠️ Voice processing error: {str(e)}"})


@app.route('/status')
def status():
    """Check Ollama status"""
    try:
        response = requests.get(f"{OLLAMA_URL}/api/tags", timeout=5)
        if response.status_code == 200:
            models = response.json().get('models', [])
            return jsonify({
                'status': 'connected',
                'models': [m['name'] for m in models],
                'current_model': DEFAULT_MODEL
            })
        else:
            return jsonify({'status': 'error', 'message': 'Ollama not responding'}), 500
    except Exception as e:
        return jsonify({'status': 'error', 'message': str(e)}), 500

if __name__ == '__main__':
    print("Starting Ollama Flask Web Interface...")
    print("Open your browser to http://localhost:5000")
    socketio.run(app, host='0.0.0.0', port=5000, debug=True)